<a href="https://colab.research.google.com/github/JDevs-py/5DATA004W_Individual_Coursework/blob/main/Dataset_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd # Importing library to load data
df = pd.read_excel('/content/1a_Median_house_price_by_region_England.xlsx', index_col = 0) # Load data and removing indexes
df # displaying it as a dataframe

,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
Year ending Sep,,,,,,,,,,,,,,,,,,,,,
North East,55000,67000,86000,95000,110000,119500,118000,113000,120000,115000,...,124950,125000,126875,129950,130000,133000,148500,142000,152000,155000
North West,63500,75500,96000,110000,120000,130000,130000,125000,130000,125000,...,138000,143000,150000,155000,159500,165000,190000,188000,200000,201250
East Midlands,76000,95000,119950,126500,132950,140000,140000,130000,138000,135000,...,150000,160000,170000,179000,182500,190000,220000,225000,235000,235000
London,170000,194000,215000,225500,238500,250000,265000,250000,284000,295000,...,387000,430000,450000,457500,455000,475000,505000,520000,525000,522500
South East,137500,160000,179000,188000,196500,215000,220000,200000,224950,224000,...,260000,286500,305000,312500,315000,322500,360000,366000,375000,370000
South West,113000,137000,157500,168000,175000,188000,190000,175000,188000,187000,...,210000,221000,235000,243000,247000,255000,287500,295000,310000,300000

In [17]:
df_transposed = df.transpose() # transposing it so name of regions appear as columns instead of rows
df_transposed

Year ending Sep,North East,North West,East Midlands,London,South East,South West
2002,55000,63500,76000,170000,137500,113000
2003,67000,75500,95000,194000,160000,137000
2004,86000,96000,119950,215000,179000,157500
2005,95000,110000,126500,225500,188000,168000
2006,110000,120000,132950,238500,196500,175000
2007,119500,130000,140000,250000,215000,188000
2008,118000,130000,140000,265000,220000,190000
2009,113000,125000,130000,250000,200000,175000
2010,120000,130000,138000,284000,224950,188000
2011,115000,125000,135000,295000,224000,187000
2012,115000,125000,135000,300000,225000,187000
2013,117000,125000,136500,319950,230000,189000
2014,120000,134000,145000,351262,243500,196000
2015,124950,138000,150000,387000,260000,210000
2016,125000,143000,160000,430000,286500,221000
2017,126875,150000,170000,450000,305000,235000
2018,129950,155000,179000,457500,312500,243000
2019,130000,159500,182500,455000,315000,247000
2020,133000,165000,190000,475000,322500,255000
2021,148500,190000,220000,505000,360000,287500
2022,142000,188000,225000,520000,366000,295000
2023,152000,200000,235000,525000,375000,310000
2024,155000,201250,235000,522500,370000,300000

In [18]:
df2 = pd.read_excel('/content/1c_Ratio_of_house_price_to_dweller_by_region.xlsx', index_col = 0) # Loading the data removing the index
df2

,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
Year,,,,,,,,,,,,,,,,,,,,,
North East,3.04,3.65,4.45,4.72,5.38,5.68,5.40,4.95,5.18,4.96,...,4.95,4.87,4.87,4.90,4.77,4.77,5.37,4.76,4.84,4.65
North West,3.29,3.77,4.59,5.02,5.44,5.69,5.45,5.21,5.35,5.17,...,5.37,5.45,5.63,5.63,5.59,5.59,6.43,6.09,6.04,5.70
East Midlands,3.89,4.69,5.73,5.76,5.99,6.21,5.90,5.30,5.64,5.55,...,5.86,6.03,6.40,6.48,6.39,6.46,7.54,7.27,7.21,6.74
London,6.74,7.40,7.95,8.00,8.32,8.38,8.52,7.83,8.87,9.26,...,11.69,12.76,12.96,12.81,12.35,12.33,13.42,13.17,12.48,11.67
South East,6.01,6.72,7.25,7.45,7.58,8.06,7.89,6.98,7.80,7.65,...,8.65,9.32,9.63,9.69,9.43,9.43,10.61,10.24,10.02,9.17
South West,5.85,6.81,7.50,7.75,7.86,8.19,7.93,7.14,7.68,7.54,...,7.93,8.25,8.54,8.56,8.44,8.45,9.73,9.28,9.08,8.31

In [19]:
df2_transposed = df2.transpose() # Transposing it so the regions are the column headers instead of rows
df2_transposed

Year  North East  North West  East Midlands  London  South East  South West
2002        3.04        3.29           3.89    6.74        6.01        5.85
2003        3.65        3.77           4.69    7.40        6.72        6.81
2004        4.45        4.59           5.73    7.95        7.25        7.50
2005        4.72        5.02           5.76    8.00        7.45        7.75
2006        5.38        5.44           5.99    8.32        7.58        7.86
2007        5.68        5.69           6.21    8.38        8.06        8.19
2008        5.40        5.45           5.90    8.52        7.89        7.93
2009        4.95        5.21           5.30    7.83        6.98        7.14
2010        5.18        5.35           5.64    8.87        7.80        7.68
2011        4.96        5.17           5.55    9.26        7.65        7.54
2012        4.84        5.07           5.40    9.23        7.64        7.47
2013        4.83        4.94           5.38    9.77        7.76        7.37
2014        4.84        5.29           5.70   10.72        8.15        7.53
2015        4.95        5.37           5.86   11.69        8.65        7.93
2016        4.87        5.45           6.03   12.76        9.32        8.25
2017        4.87        5.63           6.40   12.96        9.63        8.54
2018        4.90        5.63           6.48   12.81        9.69        8.56
2019        4.77        5.59           6.39   12.35        9.43        8.44
2020        4.77        5.59           6.46   12.33        9.43        8.45
2021        5.37        6.43           7.54   13.42       10.61        9.73
2022        4.76        6.09           7.27   13.17       10.24        9.28
2023        4.84        6.04           7.21   12.48       10.02        9.08
2024        4.65        5.70           6.74   11.67        9.17        8.31

In [23]:
df_transposed.to_csv('1a_median_price_transposed.csv') # add the title "Year" when opening the csv file
df2_transposed.to_csv('1c_ratio_transposed.csv') # add the title "Year" when opening the csv file